### ISSUE TITLE
using a function in a different package

### ISSUE THREAD

**Issue by nsheff** [pepkit/BiocProject#10]
The end of the [introductory vignette](http://code.databio.org/BiocProject/articles/1getStarted.html) promises that the next vignette explains how to use a function in a different package, but that advanced vignette fails to do so.

**Comment by michalstolarczyk** [comment]
In principle:

> The custom data processing function must take the `Project-class` as an argument 

There are no such functions outside of `BiocProject` package yet, and this is the reason why it's missing in the vignette. 

But technically it is possible

**Comment by michalstolarczyk** [comment]
The `DESeq-Packager` would be a good example of this feature if it's meant to be a standalone package

**Comment by nsheff** [comment]
well I guess we either need to create one, or remoev that wording from the vignette because it's false...
