### ISSUE TITLE
can we access the show method?

### ISSUE THREAD

**Issue by nsheff** [pepkit/BiocProject#20]
raised in conversation with @lwaldron 

Right now the `BiocProject` function with return an `Annotated` that has a `PEP` in the metadata. But when you call `show` on this it only shows you the `Annotated` part. Can we make that show function also show you the `PEP` summary?

**Comment by michalstolarczyk** [comment]
Overriding the `show` for `Annotated` would make only objects of that class (which do not exist, since it's a virtual one) use the new method. 

We would need to override the `show` for all the classes that inherit from `Annotated`, which is not possible I guess...

**Comment by nsheff** [comment]
is there a way to change the way the method lookup resolves so that it first runs our show method and then calls the other?

**Comment by nsheff** [comment]
or maybe looking back into the dual class thing would be an avenue...

**Comment by michalstolarczyk** [comment]
> is there a way to change the way the method lookup resolves so that it first runs our show method and then calls the other?

I did some web search and I don't think there's a way to influence the method dispatch

> or maybe looking back into the dual class thing would be an avenue...

What do you mean by "dual class" here?

**Comment by nsheff** [comment]
What I mean is, if it returned an `Annotated` that was *also* a `pepr::Project`, how would the `show` dispatch work? (if that's even possible...)

**Comment by michalstolarczyk** [comment]
I gave the "on the fly" method implementation another try. And it is impossible in the current environment since it is "locked":
```
 Error in setMethod("show", signature = class(readData), definition = function(object) { : 
  the environment ‘BiocProject’ is locked; cannot assign methods for function ‘show’ 
```
However, if you create a child environment while redefining the `show` method, it can be overriden for the class that is being returned:
```r
...
setMethod("show", signature = class(readData), where = new.env(parent=globalenv()), definition = function(object) { message("Testing show method") })
return(.insertPEP(readData, p))
```
and it works:
```
> bp = BiocProject(file=configFile)
Loaded config file: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/BiocProject/extdata/example_peps-master/example_BiocProject/project_config.yaml
Used function readBedFiles from the environment
> bp
Testing show method
```
the question is though, do we want to mess with the environments here?

**Comment by nsheff** [comment]
>  it is impossible in the current environment since it is "locked":

Is this just because you're doing it outside of the package?

**Comment by michalstolarczyk** [comment]
In the end the `show` method is redefined "on the fly", before the user-generated object is returned by the `BiocProject` function. The new method is defined in the environment returned by `parent.frame()` call.

 New display format:

```r
> x = S4Vectors::List(c("so","cool"))
> metadata(x) = list(PEP=pepr::Project())
> x
CharacterList of length 1
[[1]] so cool
> .setShowMethod(x)
> x
CharacterList of length 1
[[1]] so cool

metadata: PEP project object. Class:  Project
  file:  
  samples:  0
```
