### ISSUE TITLE
passing funcArgs in the yaml file

### ISSUE THREAD

**Issue by nsheff** [pepkit/BiocProject#22]
instead of doing this:

```
bpArgs = BiocProject(file="project_config.yaml", funcArgs=list(data_source="data_source", gene_names="ensembl_gene_id", gene_counts="FPKM"))
```

https://github.com/databio/DESeq-Packager#running-deseq-packager-with-bioconductor

Should we enable a way for the project_config file to specify `funcArgs` ? ideally `BiocProject` can be fully controlled from the config file.

**Comment by michalstolarczyk** [comment]
Ok. But I think we should keep the `funcArgs` argument to overwrite ones (if any) from the config since it can be useful for some fine-tuning of the data processing function. It's much more convenient to do it from within the `BiocProject` function than digging in the file every time.

**Comment by nsheff** [comment]
> we should keep the funcArgs argument to overwrite ones (if any) from the config

definitely. exactly the same as the `func` in the first place.
