### ISSUE TITLE
unit tests and checks

### ISSUE THREAD

**Issue by michalstolarczyk** [pepkit/BiocProject#23]
Write unit tests for the package

**Comment by nsheff** [comment]
along these lines -- make sure we pass R CMD check and BiocCheck.

**Comment by michalstolarczyk** [comment]
some tests pass locally but fail on travis. See: https://github.com/pepkit/BiocProject/commit/c2550361ad0b9a3b80e7e3b63d0887922e0ebc6a#commitcomment-32152991

**Comment by michalstolarczyk** [comment]
> some tests pass locally but fail on travis. See: [c255036#commitcomment-32152991](https://github.com/pepkit/BiocProject/commit/c2550361ad0b9a3b80e7e3b63d0887922e0ebc6a#commitcomment-32152991)

fixed with: 11a748a53ea0fef4e6454e467d1c33d7e8adbdff
