### ISSUE TITLE
error running vignette

### ISSUE THREAD

**Issue by nsheff** [pepkit/BiocProject#26]
I got this error running pkgdown:

```
Reading 'vignettes/vignette1getStarted.Rmd'
Error in base::basename(path, ...) : a character vector argument expected
Calls: <Anonymous> ... .f -> render_rmarkdown -> <Anonymous> -> get_result
In addition: Warning message:
no function found corresponding to methods exports from ‘BiocProject’ for: ‘config’, ‘samples’ 
Execution halted
```

are you able to regenerate the pkgdown site?

**Comment by michalstolarczyk** [comment]
Yes, I'm on `master` after you merged. The `pkgdown::build_site()` as well as `devtools::check` worked just fine.

**Comment by nsheff** [comment]
Ok it's not working for me. I have something wrong with my R setup then and I'm trying to figure it out.

did you already rebuild the docs?

**Comment by michalstolarczyk** [comment]
It was updated after I created the PR so only the changelog changed really. But I've just updated it again

**Comment by michalstolarczyk** [comment]
See https://github.com/pepkit/BiocProject/pull/25#pullrequestreview-205012438, though
