### ISSUE TITLE
update changelog to pkgdown format

### ISSUE THREAD

**Issue by nsheff** [pepkit/BiocProject#27]
https://github.com/pepkit/BiocProject/pull/25#pullrequestreview-205012438

**Comment by michalstolarczyk** [comment]
It looks like the `build_news` does not needs the title to start with a word. These do not work:

```
# [0.1.1]  - 2019-02-15
# v0.1.1  - 2019-02-15
# 0.1.1  - 2019-02-15
```

what about?

```
# BiocProject 0.1.1  - 2019-02-15
```

**Comment by nsheff** [comment]
that's much better.

**Comment by michalstolarczyk** [comment]
done
