### ISSUE TITLE
vignette feedback

### ISSUE THREAD

**Issue by nsheff** [pepkit/BiocProject#3]
@michalstolarczyk  The functionality looks great! I have a few suggestions on presentation of documenation. Can you take another revision through the vignettes? Here are some points: 

- [x] please review the general principals in [what nobody tells you about documentation](https://www.divio.com/blog/documentation/)
- [x] it's considered bad practice to call `library` inside a function; can we avoid this? instead, use fully-qualified calls. 
- [x] 'a function that processes your data'  is *not* a prereq for using `BiocProject`. all you need is a PEP. since there's only 1 prereq, I don't think you really need this section
- [x] can BiocProject install just install `pepr` automatically so we don't have to put those both in there? or does this have to wait until we release to CRAN?
- [x] the vignette can do a better job *leading* the user from simple to complex. start by demonstrating the example PEP, and reading it in. show the actual, simple PEP you're reading in (both components). show how you read this in, in one line of code, and then show how you can interact with the result -- both PEP components, and...
- [x] **then**, after that, show how the function works. right now you are starting with the function, but that hasn't been motivated.
- [x]  I cannot follow the `Usage` section
- [x] **vignettes should not have warnings**, unless you're trying to show something. (I see" Warning in makeMetadataSectionAbsolute..."). The functions either need to not warn on these, or the vignette needs to change to not trigger function warnings.
- [x] please use descriptive anchor text for links. I've already changed these.
- [x] don't just note things, show them. like, `Note that the created object is composed of both the...` -- show these things. I guess you are doing this in the next section, but this is confusing. the section needs to be able to stand on its own.
- [x] never use the phrase 'note that...' (see: https://en.wikipedia.org/wiki/Wikipedia:It_should_be_noted)
- [x] start the advanced vignette with an example function, not 'the funcArgs argument'. "Say you have a function that reads in data but takes more than just a PEP..." 
- [x] you need a section somewhere entitled 'The `autoload` argument' or 'How to suppress automatic data loading'.
- [x] please run a spellcheck, you have quite a few typos.
- [x] let's come up with a more meaningful example function for the `parseEncodeRegion_args` -- have it take an additional parameter that uses `resize` to change the width of the `GenomicRanges`, for example
- [x] please add a section/vignette demonstrating how to use it with `simpleCache`.

**Comment by nsheff** [comment]
@michalstolarczyk can you update this to indicate if you're finished with these tasks? thanks

**Comment by michalstolarczyk** [comment]
Yes, I'm done with these
