### ISSUE TITLE
Allowing data parsing functions in the pipeline interface

### ISSUE THREAD

**Issue by nsheff** [pepkit/BiocProject#34]
Right now, `BiocProject` reads a `bioconductor` section of the project config file. Doesn't it make more sense for this section to live in the pipeline interface? That way the pipeline author can specify the function to load up the data.

Perhaps it should be allowed in both places, with the project config overriding the pipeline interface.

**Comment by nsheff** [comment]
example: https://github.com/databio/pepatac/blob/b1f3667d8d022191b0e75ee3a20ceeb46cf0e426/pipeline_interface.yaml#L43-L45

**Comment by nsheff** [comment]
I've created a new branch called `piface` with some preliminary code for this.

**Comment by michalstolarczyk** [comment]
I've also added some related code, but in `pepr` on `dev`

isn't it a better place fro the pipeline interface related stuff?

**Comment by nsheff** [comment]
I think it could go either place...
