### ISSUE TITLE
Extending pipeline interface capability

### ISSUE THREAD

**Issue by nsheff** [pepkit/BiocProject#36]
We discussed using data loading from the pipelien interface in issue #34.

It would be nice if this same functionality could also be used for the new `outputs` section, and also take care of the possibility of multiple pipeline interfaces in a project, as well as the potential for one protocol to map to multiple pipelines within an interface.

**Comment by michalstolarczyk** [comment]
> It would be nice if this same functionality could also be used for the new outputs section,

it can be achieved now with, e.g.:
```r
outputsByPipeline(p, "pepatac.py")
```
